feat(deck): Use zeliblue-update in steamos-update

diff --git a/files/system_files/deck/usr/bin/steamos-update b/files/system_files/deck/usr/bin/steamos-update
--- a/files/system_files/deck/usr/bin/steamos-update
+++ b/files/system_files/deck/usr/bin/steamos-update
@@ -24,61 +24,56 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-
-if command -v ublue-update > /dev/null; then
-  if [ -n "${CHECK}" ]; then
-    if [ -f '/tmp/upgrade-installed' ]; then
-      exit 7 # Upgrade already installed
-    else
-      # Perform connectivity check
-      wget -q --spider https://github.com
-      if [ $? -eq 0 ]; then
-        # Check system state
-        ublue-update --check --updatecheck
-        if [ $? -eq 0 ]; then
-          exit 0 # Upgrade available
-        else
-          exit 7 # Checks failed
-        fi
-      else
-        exit 7 # Connectivity check failed
-      fi
-    fi
-  elif [ -n "${EXIT}" ]; then
-    exit 0
+if [ -n "${CHECK}" ]; then
+  if [ -f '/tmp/upgrade-installed' ]; then
+    exit 7 # Upgrade already installed
   else
-    # Fake upgrade progress bar
-    fake_progress() {
-      local value=0
-      while [ ! -f '/tmp/upgrade-check' ]; do
-        sleep 12
-        if [ ${value} -lt '100' ]; then
-          echo ${value}'%'
-          value=$(( value + 1 ))
-        fi
-      done
-      echo 100%
-    }
-    upgrade() {
-      # Log rotate the last session
-      if [ -f "${HOME}"/.steamos-update.log ]; then
-          cp "${HOME}"/.steamos-update.log "${HOME}"/.steamos-update.log.old
+    # Perform connectivity check
+    wget -q --spider https://github.com
+    if [ $? -eq 0 ]; then
+      # Check system state
+      /usr/bin/pkexec /usr/bin/zeliblue-update --check
+      if [ $? -eq 0 ]; then
+        exit 0 # Upgrade available
+      else
+        exit 7 # Checks failed
       fi
-
-      # Pull exit code from ublue-update
-      systemctl start ublue-update-force > "${HOME}"/.steamos-update.log 2>&1
-      echo $? > /tmp/upgrade-check
-    }
-    upgrade | fake_progress
-    # Check if upgrade failed
-    UPGRADE_CHECK=$(cat /tmp/upgrade-check)
-    rm /tmp/upgrade-check
-    if [ "${UPGRADE_CHECK}" -eq 0 ]; then
-      touch /tmp/upgrade-installed
     else
-      exit 0 # Upgrade failed
+      exit 7 # Connectivity check failed
     fi
   fi
+elif [ -n "${EXIT}" ]; then
+  exit 0
 else
-  exit 7 # ublue-update not installed
+  # Fake upgrade progress bar
+  fake_progress() {
+    local value=0
+    while [ ! -f '/tmp/upgrade-check' ]; do
+      sleep 12
+      if [ ${value} -lt '100' ]; then
+        echo ${value}'%'
+        value=$(( value + 1 ))
+      fi
+    done
+    echo 100%
+  }
+  upgrade() {
+    # Log rotate the last session
+    if [ -f "${HOME}"/.steamos-update.log ]; then
+        cp "${HOME}"/.steamos-update.log "${HOME}"/.steamos-update.log.old
+    fi
+
+    # Pull exit code from ublue-update
+    systemctl start zeliblue-update.service > "${HOME}"/.steamos-update.log 2>&1
+    echo $? > /tmp/upgrade-check
+  }
+  upgrade | fake_progress
+  # Check if upgrade failed
+  UPGRADE_CHECK=$(cat /tmp/upgrade-check)
+  rm /tmp/upgrade-check
+  if [ "${UPGRADE_CHECK}" -eq 0 ]; then
+    touch /tmp/upgrade-installed
+  else
+    exit 0 # Upgrade failed
+  fi
 fi
