chore: Update zelideck-hardware-setup
Pull in updates from upstream bazzite-hardware-setup

diff --git a/files/system_files/deck/usr/libexec/zelideck-hardware-setup b/files/system_files/deck/usr/libexec/zelideck-hardware-setup
--- a/files/system_files/deck/usr/libexec/zelideck-hardware-setup
+++ b/files/system_files/deck/usr/libexec/zelideck-hardware-setup
@@ -9,7 +9,7 @@ IMAGE_FLAVOR=$(jq -r '."image-flavor"' < $IMAGE_INFO)
 FEDORA_VERSION=$(jq -r '."fedora-version"' < $IMAGE_INFO)
 
 # SCRIPT VERSION
-HWS_VER=51
+HWS_VER=59
 HWS_VER_FILE="/etc/bazzite/hws_version"
 HWS_VER_RAN=$(cat $HWS_VER_FILE)
 
@@ -35,12 +35,6 @@ NEEDED_KARGS=()
 
 # Add directory for fixups
 mkdir -p /etc/bazzite/fixups
-
-# UPDATES
-if [[ -f /var/ublue-update/branch ]]; then
-  echo "Removing previously used branch selection file"
-  rm -f /var/ublue-update/branch
-fi
 
 # KERNEL ARGUMENTS
 echo "Current kargs: $KARGS"
@@ -68,13 +62,12 @@ if /usr/libexec/hwsupport/valve-hardware; then
     fi
   fi
 
-  echo "Turning off pstate for power consumption reasons"
-  if [[ $KARGS =~ "amd_pstate=passive" ]]; then
-    NEEDED_KARGS+=("--delete-if-present=amd_pstate=passive")
+  if [[ $KARGS =~ "amd_pstate=disable" ]]; then
+    NEEDED_KARGS+=("--delete-if-present=amd_pstate=disable")
   fi
 
-  if [[ ! $KARGS =~ "amd_pstate" ]]; then
-    NEEDED_KARGS+=("--append-if-missing=amd_pstate=disable")
+  if [[ ! $KARGS =~ "amd_pstate=passive" ]]; then
+    NEEDED_KARGS+=("--append-if-missing=amd_pstate=passive")
   fi
 fi
 
@@ -86,6 +79,12 @@ if [[ $IMAGE_NAME =~ "deck" && ":AOKZOE A1 AR07:" =~ ":$SYS_ID:" ]]; then
 fi
 
 if [[ ":Framework:" =~ ":$VEN_ID:" ]]; then
+  if [[ "$SYS_ID" == "Laptop 16 ("* ]]; then
+    if [[ ! $KARGS =~ "amdgpu.dcdebugmask" ]]; then
+      echo "Framework 16 Laptop detected, fixing display artifacts"
+      NEEDED_KARGS+=("--append-if-missing=amdgpu.dcdebugmask=0x410")
+    fi
+  fi
   if [[ "AuthenticAMD" == "$CPU_VENDOR" ]]; then
     if [[ ! $KARGS =~ "iomem" ]]; then
       echo "AMD Framework Laptop detected, adding needed kargs for ryzenadj"
@@ -145,9 +144,9 @@ elif [[ ":WIN2:" =~ ":$SYS_ID:" ]]; then
   fi
 fi
 
-if [[ ":ONEXPLAYER F1:ONEXPLAYER F1L:ONEXPLAYER F1 EVA-01:" =~ ":$SYS_ID:" ]]; then
+if [[ ":ONEXPLAYER F1:ONEXPLAYER F1L:ONEXPLAYER F1 EVA-01:ONEXPLAYER X1Pro:" =~ ":$SYS_ID:" ]]; then
   if [[ ! $KARGS =~ "video" ]]; then
-    echo "Adding panel orientation for ONEXPLAYER F1 & ONEXFLY"
+    echo "Adding panel orientation for ONEXPLAYER F1, ONEXFLY, & X1 Pro"
     NEEDED_KARGS+=("--append-if-missing=video=eDP-1:panel_orientation=left_side_up")
   fi
   if [[ "$(awk '/MemTotal/{print $(NF-1)}' /proc/meminfo)" == "31664740" ]]; then
@@ -155,6 +154,13 @@ if [[ ":ONEXPLAYER F1:ONEXPLAYER F1L:ONEXPLAYER F1 EVA-01:" =~ ":$SYS_ID:" ]]; t
       echo "Adding GTTSize for ONEXPLAYER (32GB RAM)"
       NEEDED_KARGS+=("--append-if-missing=amdgpu.gttsize=16256")
     fi
+  fi
+fi
+
+if [[ ":ROG Flow Z13 GZ302EA:" =~ "$:SYS_ID:" ]]; then
+  if [[ ! $KARGS =~ "amdgpu.dcdebugmask" ]]; then
+    echo "ROG Flow Z13 2025, fixing display artifacts"
+    NEEDED_KARGS+=("--append-if-missing=amdgpu.dcdebugmask=0x410")
   fi
 fi
 
@@ -205,6 +211,7 @@ if [[ $IMAGE_NAME =~ "deck" || $IMAGE_NAME =~ "ally" ]]; then
     systemctl disable --now ryzenadj.service
     systemctl disable --now batterylimit.service
   fi
+  systemctl enable --now ds-inhibit.service
 fi
 
 # FSTAB CONFIGURATION
@@ -254,10 +261,61 @@ if [[ ":Framework:" =~ ":$VEN_ID:" ]]; then
   fi
 fi
 
+# SURFACE FIXES
+if [[ ":Microsoft:" =~ ":$VEN_ID:" ]]; then
+  if ! [[ -f "/etc/modules-load.d/surface.conf" ]]; then
+    if [[ "AuthenticAMD" == "$CPU_VENDOR" ]]; then
+      printf "# Support GPIO pins on AMD Surfaces\npinctrl_amd\n" > "/etc/modules-load.d/surface.conf"
+    elif [[ "GenuineIntel" == "$CPU_VENDOR" ]]; then
+      sed 's/^ *//' > "/etc/modules-load.d/surface.conf" << EOF
+        # Support GPIO pins on Intel Surfaces
+        # Surface Book 2
+        pinctrl_sunrisepoint
+
+        # For Surface Laptop 3/Surface Book 3
+        pinctrl_icelake
+
+        # For Surface Laptop 4/Surface Laptop Studio
+        pinctrl_tigerlake
+
+        # For Surface Pro 9/Surface Laptop 5
+        pinctrl_alderlake
+
+        # For Surface Pro 10/Surface Laptop 6
+        pinctrl_meteorlake
+
+        # Support LPSS on Intel Surfaces
+        intel_lpss
+        intel_lpss_pci
+
+EOF
+    fi
+    sed 's/^ *//' >> "/etc/modules-load.d/surface.conf" << EOF
+      # Add modules necessary for Disk Encryption via keyboard
+      surface_aggregator
+      surface_aggregator_registry
+      surface_aggregator_hub
+      surface_hid_core
+      8250_dw
+
+      # Surface Laptop 3/Surface Book 3 and later
+      surface_hid
+      surface_kbd
+EOF
+  fi
+fi
+
 # WAYDROID FIX
 if [[ -f "/var/lib/waydroid/lxc/waydroid/config" ]]; then
   echo "Removing unneeded apparmor entry from Waydroid LXC"
   sed -i '/lxc\.apparmor\.profile\s*=\s*unconfined/d' "/var/lib/waydroid/lxc/waydroid/config"
+fi
+
+# HOSTNAME FIX
+# If the hostname is too long Distrobox will fail during setup
+# Let's check the length and reset it to something sensible if that happens.
+if (( $(hostname | wc -m) > 20 )); then
+  hostnamectl set-hostname bazzite
 fi
 
 # PPD FIX
@@ -289,6 +347,79 @@ if [ ! -f /etc/bazzite/fixups/snapper_cleanup ] &&
   snapper -c root delete-config
 fi
 touch /etc/bazzite/fixups/snapper_cleanup
+
+if [ ! -f /etc/bazzite/fixups/grub_fixup ]; then
+  # Grub settings
+  # Set grub timeout to 3 seconds
+  if [ -z $(grep "GRUB_TIMEOUT=" /etc/default/grub) ]; then
+    echo "GRUB_TIMEOUT=3" >> /etc/default/grub
+  else
+    sed -i 's/GRUB_TIMEOUT=[0-9]*/GRUB_TIMEOUT=3/' /etc/default/grub
+  fi
+
+  # Nuke hidden timeout as it will cause issues if GRUB_TIMEOUT exists
+  if [ -n $(grep "GRUB_HIDDEN_TIMEOUT=" /etc/default/grub) ]; then
+    sed -i 's/GRUB_HIDDEN_TIMEOUT=[0-9]*//' /etc/default/grub
+  fi
+
+  # set timeout style to menu to show grub during countdown
+  # (unless GRUB_TIMEOUT=0)
+  if [ -z $(grep "GRUB_TIMEOUT_STYLE=" /etc/default/grub) ]; then
+    echo "GRUB_TIMEOUT_STYLE=menu" >> /etc/default/grub
+  else
+    sed -i 's/GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT_STYLE=menu/' /etc/default/grub
+  fi
+
+  # Autohide grub menu if boot is successful
+  # menu_auto_hide=2 hides grub menu if previous boot is successful
+  # menu_auto_hide=1 same, except not if Windows/Other OS is installed
+  # Deck images cant use grub menu and often dual boot, so hide it always
+  # For desktop images, hide it only if no other OS is installed
+  if [[ $IMAGE_NAME =~ "deck" ]]; then
+    grub2-editenv - set menu_auto_hide=2
+  else
+    grub2-editenv - set menu_auto_hide=1
+  fi
+
+  # Update grub
+  if [ -d /sys/firmware/efi ]; then
+    echo "Updating EFI grub config"
+    grub2-mkconfig -o /etc/grub2-efi.cfg
+  else
+    echo "Updating BIOS grub config"
+    grub2-mkconfig -o /etc/grub2.cfg
+  fi
+fi
+touch /etc/bazzite/fixups/grub_fixup
+
+# Fix users who've layered CoolerControl in the past.
+if [ ! -f /etc/bazzite/fixups/coolercontrol_fixup ]; then
+  if rpm-ostree status --booted | grep -q "coolercontrol"; then
+      sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/terra.repo
+  fi
+  touch /etc/bazzite/fixups/coolercontrol_fixup
+fi
+
+# Fix users who've layered LACT in the past.
+if [ ! -f /etc/bazzite/fixups/lact_fixup ]; then
+  if rpm-ostree status --booted | grep -q "lact"; then
+      dnf5 -y copr enable ilyaz/LACT
+  fi
+  touch /etc/bazzite/fixups/lact_fixup
+fi
+
+# Fix users who've layered CDEmu in the past.
+if [ ! -f /etc/bazzite/fixups/cdemu_fixup ]; then
+  if rpm-ostree status --booted | grep -q "cdemu-daemon"; then
+      dnf5 -y copr enable rok/cdemu
+  fi
+  touch /etc/bazzite/fixups/cdemu_fixup
+fi
+
+# Fix missing hostname file breaking distrobox
+if [ ! -f /etc/hostname ]; then
+  touch /etc/hostname
+fi
 
 mkdir -p /etc/bazzite
 echo $HWS_VER > $HWS_VER_FILE
