chore(flatpaks): Merge changes from upstream branch

diff --git a/modules/flatpaks/files/bin/system-flatpak-setup b/modules/flatpaks/files/bin/system-flatpak-setup
--- a/modules/flatpaks/files/bin/system-flatpak-setup
+++ b/modules/flatpaks/files/bin/system-flatpak-setup
@@ -13,9 +13,19 @@ fi
 
 # Opt out of and remove Fedora's flatpak repo
 if grep -qz 'fedora' <<< $(flatpak remotes); then
+  /usr/bin/gnome-software --quit
   /usr/lib/fedora-third-party/fedora-third-party-opt-out
   /usr/bin/fedora-third-party disable
   flatpak remote-delete fedora --force
+  flatpak remote-delete fedora-testing --force
+
+  # Remove flatpak apps from origin fedora
+  FEDORA_FLATPAKS=$(flatpak list --app --columns=application,origin | grep -w 'fedora' | awk '{print $1}')
+  flatpak remove --system --noninteractive ${FEDORA_FLATPAKS[@]}
+
+  # Remove flatpak runtimes from origin fedora
+  FEDORA_FLATPAKS=$(flatpak list --runtime --columns=application,arch,branch,origin | grep -w 'fedora' | awk '{print $1"/"$2"/"$3}')
+  flatpak remove --system --noninteractive ${FEDORA_FLATPAKS[@]}
 fi
 
 REPO_INFO="/etc/flatpak/system/repo-info.yml"
@@ -25,19 +35,21 @@ REPO_TITLE=$(yq '.repo-title' $REPO_INFO)
 
 # Set up system-wide Flatpak repository
 if [[ ! $REPO_URL == "null" && ! $REPO_NAME == "null" ]]; then
-    flatpak remote-add --if-not-exists --system $REPO_NAME $REPO_URL
+  echo "Adding system-wide remote $REPO_NAME from $REPO_URL"
+  flatpak remote-add --if-not-exists --system $REPO_NAME $REPO_URL
 fi
 
 # If configured remote is flathub, enable it here.
 # Flathub is already installed on Fedora, but not enabled by default,
 # so the above command won't add it again
 if [[ $REPO_NAME == "flathub" ]]; then
-    flatpak remote-modify --system $REPO_NAME --enable
+  flatpak remote-modify --system $REPO_NAME --enable
 fi
 
 # Change repository title to configured title, if not null
 if [[ ! $REPO_TITLE == "null" ]]; then
-    flatpak remote-modify --system $REPO_NAME --title="$REPO_TITLE"
+  echo "Setting title $REPO_TITLE for remote $REPO_NAME"
+  flatpak remote-modify --system $REPO_NAME --title="$REPO_TITLE"
 fi
 
 # Lists of flatpaks
@@ -47,20 +59,15 @@ REMOVE_LIST=$(cat /etc/flatpak/system/remove)
 
 # Install flatpaks in list
 if [[ -n $INSTALL_LIST ]]; then
-  for flatpak in $INSTALL_LIST; do
-    if grep -qvz $flatpak <<< $FLATPAK_LIST; then
-      flatpak install --system --noninteractive $REPO_NAME $flatpak
-    fi
-  done
+  if ! flatpak install --system --noninteractive $REPO_NAME ${INSTALL_LIST[@]}; then
+    # Exit on error
+    exit 1
+  fi
 fi
 
 # Remove flatpaks in list
 if [[ -n $REMOVE_LIST ]]; then
-  for flatpak in $REMOVE_LIST; do
-    if grep -qz $flatpak <<< $FLATPAK_LIST; then
-      flatpak remove --system --noninteractive $flatpak
-    fi
-  done
+  flatpak remove --system --noninteractive ${REMOVE_LIST[@]}
 fi
 
 # Prevent future executions
diff --git a/modules/flatpaks/files/bin/user-flatpak-setup b/modules/flatpaks/files/bin/user-flatpak-setup
--- a/modules/flatpaks/files/bin/user-flatpak-setup
+++ b/modules/flatpaks/files/bin/user-flatpak-setup
@@ -14,6 +14,7 @@ fi
 # Remove Fedora's flatpak repo, if it exists
 if grep -qz 'fedora' <<< $(flatpak remotes); then
   flatpak remote-delete --user fedora --force
+  flatpak remote-delete --user fedora-testing --force
 fi
 
 REPO_INFO="/etc/flatpak/user/repo-info.yml"
@@ -23,12 +24,14 @@ REPO_TITLE=$(yq '.repo-title' $REPO_INFO)
 
 # Set up per-user Flatpak repository
 if [[ ! $REPO_URL == "null" && ! $REPO_NAME == "null" ]]; then
-    flatpak remote-add --if-not-exists --user $REPO_NAME $REPO_URL
+  echo "Adding remote $REPO_NAME from $REPO_URL"
+  flatpak remote-add --if-not-exists --user $REPO_NAME $REPO_URL
 fi
 
 # Change repository title to configured title, if not null
 if [[ ! $REPO_TITLE == "null" ]]; then
-    flatpak remote-modify --user $REPO_NAME --title="$REPO_TITLE"
+  echo "Setting title $REPO_TITLE for remote $REPO_NAME"
+  flatpak remote-modify --user $REPO_NAME --title="$REPO_TITLE"
 fi
 
 # Lists of flatpaks
@@ -38,20 +41,15 @@ REMOVE_LIST=$(cat /etc/flatpak/user/remove)
 
 # Install flatpaks in list
 if [[ -n $INSTALL_LIST ]]; then
-  for flatpak in $INSTALL_LIST; do
-    if grep -qvz $flatpak <<< $FLATPAK_LIST; then
-      flatpak install --user --noninteractive $REPO_NAME $flatpak
-    fi
-  done
+  if ! flatpak install --user --noninteractive $REPO_NAME ${INSTALL_LIST[@]}; then
+    # Exit on error
+    exit 1
+  fi
 fi
 
 # Remove flatpaks in list
 if [[ -n $REMOVE_LIST ]]; then
-  for flatpak in $REMOVE_LIST; do
-    if grep -qz $flatpak <<< $FLATPAK_LIST; then
-      flatpak remove --user --noninteractive $flatpak
-    fi
-  done
+  flatpak remove --user --noninteractive $flatpak ${REMOVE_LIST[@]}
 fi
 
 # Prevent future executions
